apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb-statefulset
spec:
  serviceName: postgresdb-service
  replicas: 1  # сколько подов требуется в стейтфулсете
  template:
    metadata:
      labels:
        # label нужен из тех же соображений, что и в деплойменте.
        app: postgresdb-app
    spec:
      containers:
        - name: postgresdb-container
          image: postgres:15
          volumeMounts:
            - mountPath: "/data/db"
              name: postgresdb-pvc
          # Выставляем наружу дефолтный порт монги.
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: administration
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres

  # selector нужен из тех же соображений, что и в деплойменте.
  selector:
    matchLabels:
      app: postgresdb-app
  volumeClaimTemplates:
    - metadata:
        name: postgresdb-pvc
      spec:
        accessModes:
          - ReadWriteOnce # можно читать/писать только на одной ноде
        resources:
          requests:
            storage: 100Mi
